name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      placeholder: e.g. 1.0.0
    validations:
      required: true
  - type: input
    id: ide-version
    attributes:
      label: IDE Version
      placeholder: e.g. IntelliJ IDEA 2023.3
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform / OS
      placeholder: e.g. Windows 11, macOS Sonoma
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How did you encounter the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
