name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: behavior
    attributes:
      label: Desired Behavior
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why do you need this feature?
